# Generated by Django 4.0.1 on 2022-01-16 15:44

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'lountry',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europeanfootball.country')),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_short_name', models.CharField(max_length=255)),
                ('team_long_name', models.CharField(max_length=255)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europeanfootball.league')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Matchstats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('home_team_id', models.IntegerField()),
                ('away_team_id', models.IntegerField()),
                ('home_team_goal', models.IntegerField()),
                ('away_team_goal', models.IntegerField()),
                ('goals_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None), size=None)),
                ('card_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('corner_info', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None), size=None)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='europeanfootball.league')),
            ],
            options={
                'db_table': 'matchstats',
            },
        ),
    ]
